services:
  backend:
    build: ./backend
    container_name: cinematch-backend
    ports:
      - "8080:8080"
    env_file:
      - .env

  frontend:
    image: nginx:alpine
    container_name: cinematch-frontend
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend